#!/bin/bash
echo 'this is kernel file'
# gcc -c -o main.o main.c
# ld main.o -Ttext 0xc0001500 -e main -o kernel.bin

#我之前gcc是加了-m32参数的，所以生成的.o文件是32位
#这个链接过程要加-m elf_i386的原因是ld默认链接64位，与32位.o不匹配
# gcc -m32 -c -o main.o main.c
# ld -m elf_i386 main.o -Ttext 0xc0001500 -e main -o kernel.bin
# dd if=kernel.bin of=/home/huust/bochs_config/rieos_boot.img bs=512 count=200 seek=9 conv=notrunc

#与print的编译链接过程
# nasm -f elf -o print.o print.asm
# gcc -m32 -I ../ -c -o main.o main.c
# ld -m elf_i386 -Ttext 0xc0001500 -e main -o kernel.bin main.o print.o
# dd if=kernel.bin of=/home/huust/bochs_config/rieos_boot.img bs=512 count=200 seek=9 conv=notrunc


#中断部分的编译链接过程
nasm -f elf -o build/print.o print.asm
nasm -f elf -o build/kernel.o kernel.asm

gcc -m32 -I ../ -I ./ -c -fno-stack-protector -o build/main.o main.c

gcc -m32 -I ../ -I ./ -c -fno-stack-protector -o build/interrupt.o interrupt.c

gcc -m32 -I ../ -I ./ -c -fno-stack-protector -o build/debug.o debug.c

ld -m elf_i386 -Ttext 0xc0001500 -e main -o kernel.bin build/main.o build/debug.o build/print.o build/kernel.o build/interrupt.o

dd if=kernel.bin of=/home/huust/bochs_config/rieos_boot.img bs=512 count=200 seek=9 conv=notrunc
